// This file is auto-generated by scripts/generate-build-info.js
// Do not edit manually.
export interface BuildInfoMeta {
  generatedAt: string;
  frontend: BuildInfoEntry;
  backend: BuildInfoEntry;
}
export interface BuildInfoEntry {
  buildTimestamp?: string;
  commit?: string;
}
export const BUILD_INFO: BuildInfoMeta = {
  "generatedAt": "2026-09-05T17:08:11.341Z",
  "frontend": {
    "buildTimestamp": "2025-11-11T20:30:09+01:00",
    "commit": "ba003a7d49586e109b3666edbb33d3700bdd3604"
  },
  "backend": {
    "buildTimestamp": "2026-05-20T11:47:41+02:00",
    "commit": "332b924a60b9ba020b35d815debd4ae5d275a0cf"
  }
};
