// This file is auto-generated by scripts/generate-build-info.js
// Do not edit manually.
export interface BuildInfoMeta {
  generatedAt: string;
  frontend: BuildInfoEntry;
  backend: BuildInfoEntry;
}
export interface BuildInfoEntry {
  buildTimestamp?: string;
  commit?: string;
}
export const BUILD_INFO: BuildInfoMeta = {
  "generatedAt": "2025-10-06T09:12:37.214Z",
  "frontend": {
    "buildTimestamp": "2025-10-02T17:13:25+02:00",
    "commit": "e61c58696e1db67b189977f6f5276f7d412809a0"
  },
  "backend": {
    "buildTimestamp": "2025-10-02T16:48:39+02:00",
    "commit": "106aaa33e889535584ae7d0b14a47052d5fb72f3"
  }
};
