// This file is auto-generated by scripts/generate-build-info.js
// Do not edit manually.
export interface BuildInfoMeta {
  generatedAt: string;
  frontend: BuildInfoEntry;
  backend: BuildInfoEntry;
}
export interface BuildInfoEntry {
  buildTimestamp?: string;
  commit?: string;
}
export const BUILD_INFO: BuildInfoMeta = {
  "generatedAt": "2026-09-12T15:40:21.016Z",
  "frontend": {
    "buildTimestamp": "2026-09-12T09:55:43+02:00",
    "commit": "4c3b67acfb2ad4e7083153b1c660592c2bd21868"
  },
  "backend": {
    "buildTimestamp": "2026-09-12T09:55:43+02:00",
    "commit": "4c3b67acfb2ad4e7083153b1c660592c2bd21868"
  }
};
