name: Docker Build and Push

permissions:
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: frontend
            context: ./Frontend
            dockerfile: ./Frontend/Dockerfile
            tag: frontend:dev
          - name: backend
            context: ./Backend
            dockerfile: ./Backend/Dockerfile
            tag: backend:dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push ${{ matrix.image.name }} Docker image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.image.context }}
          file: ${{ matrix.image.dockerfile }}
          push: true
          tags: ${{ matrix.image.name == 'frontend' && secrets.DOCKER_REPO_FRONT || secrets.DOCKER_REPO_BACK }}:dev
