name: Frontend Build Check

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches: [ "main" ]
    paths: # Optional: Only run if files in Frontend directory change
      - 'Frontend/**'
      - '.github/workflows/frontend-build.yml'

  # Trigger the workflow on pull request events targeting the main branch
  pull_request:
    branches: [ "main" ]
    paths: # Optional: Only run if files in Frontend directory change
      - 'Frontend/**'
      - '.github/workflows/frontend-build.yml'

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest # Use a standard Linux runner

    # Define default working directory for steps that need it
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Documentation: https://github.com/pnpm/action-setup
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Specify your desired pnpm version, or omit for latest

      # Documentation: https://github.com/actions/setup-node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Specify the Node.js version your project uses
          # You can use LTS versions like '18.x', '20.x', or specific versions '18.17.0'
          # Or read from a .node-version file: node-version-file: './Frontend/.node-version'
          node-version: '20.x'
          # Cache pnpm dependencies based on the lock file
          cache: 'pnpm'
          cache-dependency-path: './Frontend/pnpm-lock.yaml' # Important: Path relative to repo root

      - name: Install Dependencies
        # No need for working-directory here if set in defaults
        run: pnpm install --frozen-lockfile # Use --frozen-lockfile for CI consistency

      - name: Build Frontend Application
        # Replace 'build' with the actual name of your build script in package.json
        # e.g., build:prod, generate, etc.
        run: pnpm run build

      # Optional: Add a step to upload build artifacts if needed
      # - name: Upload Build Artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: frontend-build
      #     path: ./Frontend/dist # Adjust path to your build output directory
